### ISSUE TITLE
Report expects "row-number" key

### ISSUE THREAD

**Issue by cschloer** [frictionlessdata/goodtables-ui#25]
# Overview

Hi,
I'm trying to use the UI to show a simple report of a repeated column name. The report is as follows:
```
{
          "error-count": 1,
          "preset": "table",
          "table-count": 1,
          "tables": [
            {
              "encoding": "utf-8",
              "error-count": 1,
              "errors": [
                {
                  "code": "duplicate-header",
                  "column-number": 5,
                  "message": "Header in column 5 is duplicated to header in column(s) 4",
                  "message-data": {
                    "column_numbers": "4",
                    "original": "4"
                  }
                }
              ],
              "format": "csv",
              "headers": [
                "col1",
                "col2",
                "col3",
                "col4",
                "col4"
              ],
              "row-count": 5,
              "schema": "table-schema",
              "scheme": "s3",
              "source": "s3://submissions/testing5/files/test2.csv",
              "time": 0.079,
              "valid": false
            }
          ],
          "time": 0.102,
          "valid": false,
          "warnings": null
        }
},
```
The line here https://github.com/frictionlessdata/goodtables-ui/blob/master/src/helpers.js#L51 assumes that there is a 'row-number' key in the error dict. Because there isn't, the resulting structure looks something like:
![Screenshot from 2020-01-13 11-25-50](https://user-images.githubusercontent.com/7134143/72248458-8141f880-35f7-11ea-8eee-039a439638f1.png)
As you can see, the rows key has undefined as a value in the dictionary. Down the line this ends up leading to an error in ErrorGroupTable here https://github.com/frictionlessdata/goodtables-ui/blob/master/src/components/ErrorGroup.js#L113
`TypeError: errorGroup.rows[rowNumber] is undefined`

I think at some point the undefined value is converted into a null value and then it leads to this error.

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by cschloer** [comment]
My super quick fix was to add a `.filter(v => !!v)` to the rowNumbers line in  https://github.com/frictionlessdata/goodtables-ui/blob/master/src/components/ErrorGroup.js#L109

**Comment by cschloer** [comment]
Now I'm a bit confused because this report works properly on the demo

**Comment by cschloer** [comment]
The better fix was to replace
`group.rows[error['row-number']] = row`
with 
```
if (error['row-number']) {
group.rows[error['row-number']] = row
} else {
group.rows[1] = row
}
```
inside of helpers.js

**Comment by cschloer** [comment]
Sorry, didn't do too much looking into this. Seems like it's unrelated to whether the error has a row/column number or not:

Just had the same error with this report:
```
{
          "error-count": 2,
          "preset": "table",
          "table-count": 1,
          "tables": [
            {
              "encoding": "utf-8",
              "error-count": 2,
              "errors": [
                {
                  "code": "blank-header",
                  "column-number": 5,
                  "message": "Header in column 5 is blank",
                  "message-data": {}
                },
                {
                  "code": "duplicate-row",
                  "message": "Row 6 is duplicated to row(s) 2",
                  "message-data": {
                    "row_numbers": "2"
                  },
                  "row-number": 6
                }
              ],
              "format": "csv",
              "headers": [
                "col1",
                "col2",
                "col3",
                "col4",
                ""
              ],
              "row-count": 8,
              "schema": "table-schema",
              "scheme": "s3",
              "source": "test_errors.csv",
              "time": 0.044,
              "valid": false
            }
          ],
          "time": 0.102,
          "valid": false,
          "warnings": null
        }
      }
```

These reports are all generated by files being run through goodtables in the backend.

**Comment by roll** [comment]
@cschloer 
I think it's related to breaking changes introduced in `goodtables@2` - https://github.com/frictionlessdata/testsuite-extended/issues/27

**Comment by cschloer** [comment]
Yeah that seems about right. For now I can update my Backend Code to add
those keys while I'm developing. Will the longer term solution be fixing
goodtables or adjusting goodtables-ui?

roll <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 14:56:

**Comment by roll** [comment]
@cschloer 
Let me think. I'll be on it in around a week. 

My intention had been not to have optional keys on `report.json` but we had kinda mixed decision-making back to the v2 release so this idea was dropped.

If, for now, you can populate these keys on your side it will be great

**Comment by cschloer** [comment]
Sounds good. Hope you had a great vacation!

roll <notifications@github.com> schrieb am Mo., 13. Jan. 2020, 15:28:

**Comment by cschloer** [comment]
FYI I just reverted back to goodtables v1.5.1 as there was some other data missing in the report of the newer version

**Comment by roll** [comment]
@cschloer 
Could you please try a version from https://github.com/frictionlessdata/goodtables-ui/pull/27?

**Comment by cschloer** [comment]
Responded on the PR

**Comment by cschloer** [comment]
:+1:
