### ISSUE TITLE
Feature request: goodtables unspecific verbosity

### ISSUE THREAD

**Issue by cschloer** [frictionlessdata/goodtables-ui#26]
# Overview

We plan to use goodtables in a context where the front end user has no idea that goodtables is being used to validate the dataset, nor do they have any ability to change goodtables parameters, etc.

It would be great if there was a flag in goodtables-ui that lets you specify that you don't want any error detail text that relates to goodtables. Such as:
`If this error should be ignored disable duplicate-header check in goodtables.yml.`

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Adding some context also

It comes from this line
- https://github.com/frictionlessdata/goodtables-ui/blob/master/src/components/ErrorGroup.js#L163

Combined with the spec:
- https://github.com/frictionlessdata/data-quality-spec/blob/master/spec.json
